import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import type { Brief } from "@/lib/api/schemas";

import { BriefPanel } from "./brief-panel";

const base: Brief = {
  id: "11111111-1111-1111-1111-111111111111",
  incident_id: "22222222-2222-2222-2222-222222222222",
  version: 1,
  status: "complete",
  source: "perplexity",
  packet_hash: "a".repeat(64),
  packet_truncated: false,
  model: "sonar",
  summary: "asset-A did four things.",
  limitations: "No process context.",
  claims: [],
  recommendations: [],
  citations: [],
  has_unverified: false,
  failure_reason: null,
  created_at: "2026-09-06T12:00:00Z",
};

const brief = (overrides: Partial<Brief> = {}): Brief => ({ ...base, ...overrides });
const render = (briefs: Brief[]) => renderToStaticMarkup(<BriefPanel briefs={briefs} />);

describe("what the panel is obliged to say", () => {
  it("says a case has no brief rather than showing an empty one", () => {
    expect(render([])).toContain("No brief has been generated");
  });

  it("labels the committed sample as not a model", () => {
    const html = render([brief({ source: "offline_fixture", model: null })]);
    expect(html).toContain("offline sample");
    expect(html).toContain("not something a model wrote");
  });

  it("does not badge a failed brief as generated", () => {
    // The badge is the only place the page states provenance, and a failed brief was not
    // generated by anything — the sentence right below it says so.
    const html = render([brief({ status: "failed", summary: null, failure_reason: "http_503" })]);
    expect(html).toContain("not generated");
    expect(html).not.toContain(">generated<");
    expect(html).toContain("The API answered 503.");
  });

  it("marks an uncited external claim rather than dropping it", () => {
    const html = render([
      brief({
        has_unverified: true,
        claims: [
          { text: "CVE-2026-9999 is exploited.", kind: "external", citations: [], verified: false },
          { text: "asset-A reached 40 ports.", kind: "observed", citations: [], verified: true },
        ],
      }),
    ]);
    expect(html.match(/UNVERIFIED/g) ?? []).toHaveLength(2); // once per claim, once on the header
    expect(html).toContain("CVE-2026-9999 is exploited.");
  });

  it("says these are things to look at, not things to do", () => {
    const html = render([
      brief({ recommendations: [{ action: "investigate_host", detail: "Look at it." }] }),
    ]);
    expect(html).toContain("Investigate the host");
    expect(html).toContain("not things to do to a system");
  });

  it("counts the earlier versions it is not showing", () => {
    const html = render([brief({ version: 3 }), brief({ version: 2 }), brief({ version: 1 })]);
    expect(html).toContain("2 earlier versions");
    expect(html).toContain("never edited or replaced");
  });
});

describe("a reason or an action this app has never heard of", () => {
  // `failure_reason` and `action` are unconstrained strings on purpose, so a value the domain
  // adds later shows itself instead of blanking the page. `in` would walk Object.prototype.
  const prototypeKeys = ["toString", "constructor", "hasOwnProperty", "valueOf", "__proto__"];

  it.each(prototypeKeys)("shows the failure reason %s as itself", (reason) => {
    const html = render([brief({ status: "failed", summary: null, failure_reason: reason })]);
    expect(html).toContain(reason);
    expect(html).toContain("The request did not complete");
  });

  it.each(prototypeKeys)("shows the recommendation action %s as itself", (action) => {
    const html = render([brief({ recommendations: [{ action, detail: "" }] })]);
    expect(html).toContain(action);
  });

  it("shows an unfamiliar reason code rather than nothing", () => {
    const html = render([
      brief({ status: "failed", summary: null, failure_reason: "quota_exhausted_v2" }),
    ]);
    expect(html).toContain("quota_exhausted_v2");
  });
});
